version: 'serverapp'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/serverapp
      - /usr/src/serverapp/node_modules
    #command: yarn start
    command: yarn dev
    depends_on:
      - database_postgres

  database_postgres:
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "reactexpressjs"
      POSTGRES_PASSWORD: "secret"

    container_name: "bdreact"
    volumes:
      - ./postgres:/var/lib/postgresql/data

#ESTE ARCHIVO ES PARA USO DE LA APLICACION LOCAL EN DOCKER.COMPOSE USANDO LOS COMANDOS DE :
#COMANDO PARA EJECUTAR DOCKER.COMPOSE.YML
#docker-compose up --build